#Machine Learning e Data Science com Python de A a Z - Agrupamento

In [1]:
!pip install plotly --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 31.6 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.15.0
    Uninstalling plotly-5.15.0:
      Successfully uninstalled plotly-5.15.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.


In [2]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

##K-means

###Base idade e salário

In [3]:
from sklearn.cluster import KMeans

In [7]:
x = [20, 27, 21, 37, 46, 53, 55, 47, 52, 32, 39, 41, 39, 48, 48]
y = [1000, 1200, 2900, 1850, 900, 950, 2000, 2100, 3000, 5900, 4100, 5100, 7000, 5000, 6500]

In [8]:
grafico = px.scatter(x =x , y = y)
grafico.show()

In [9]:
base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])

In [10]:
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [12]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [13]:
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [15]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



KMeans(n_clusters=3)

In [16]:
centroides = kmeans_salario.cluster_centers_
centroides

array([[-1.63312883, -0.77505093],
       [ 0.73953003, -0.72661025],
       [ 0.07703438,  1.11413572]])

In [17]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  22.66666667, 1700.        ],
       [  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ]])

In [18]:
rotulos = kmeans_salario.labels_

In [19]:
rotulos

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int32)

In [21]:
grafico1 = px.scatter(x = base_salario[:, 0], y = base_salario[:, 1], color=rotulos)
grafico2 = px.scatter(x = centroides[:, 0], y = centroides[:, 1], size=[12, 12, 12])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

###Dados randômicos

In [22]:
from sklearn.datasets import make_blobs


In [34]:
x_random, y_random = make_blobs(n_samples=200, centers=5)


In [35]:
x_random

array([[ -1.78634495,   2.44503252],
       [  0.65166256,   4.94630329],
       [  4.07190495,   6.09869803],
       [  3.46041764,   5.99579392],
       [  0.13791894,   2.53552003],
       [ -0.37158578,   1.18371741],
       [ -9.56146628,  -8.38678506],
       [  4.13510493,  -5.99765827],
       [-10.52493667,  -8.1768423 ],
       [  1.93034189,   4.48075694],
       [  3.42761089,   5.92797898],
       [ 10.26004354,  -7.98766747],
       [  0.54387841,   2.91704521],
       [  9.15989146,  -6.94965582],
       [ -8.78722507,  -7.1173002 ],
       [  2.57303758,   6.28317195],
       [ -0.03730271,   1.80014334],
       [-10.00751117,  -8.50719585],
       [  8.13476515,  -8.54423582],
       [  0.07882512,   2.5927906 ],
       [  4.7216375 ,  -4.30050923],
       [  2.60987716,  -3.8961444 ],
       [-10.35108084,  -8.36218633],
       [-10.39692629, -10.58290884],
       [  8.70190556,  -8.08245209],
       [  2.87726484,   6.17971047],
       [  0.38424924,   1.55413727],
 

In [36]:
y_random

array([3, 1, 1, 1, 3, 3, 0, 2, 0, 1, 1, 4, 3, 4, 0, 1, 3, 0, 4, 3, 2, 2,
       0, 0, 4, 1, 3, 4, 1, 1, 1, 1, 1, 2, 4, 0, 4, 0, 2, 2, 2, 0, 0, 1,
       4, 3, 0, 1, 1, 3, 4, 3, 3, 4, 0, 1, 0, 3, 2, 3, 0, 2, 1, 1, 0, 4,
       3, 0, 1, 1, 4, 3, 0, 4, 1, 0, 2, 1, 2, 1, 0, 2, 4, 0, 2, 4, 4, 3,
       3, 2, 0, 2, 4, 0, 2, 1, 3, 0, 4, 4, 0, 4, 1, 3, 2, 1, 4, 0, 4, 2,
       3, 2, 2, 2, 4, 2, 1, 3, 3, 3, 1, 1, 3, 2, 4, 3, 4, 2, 3, 1, 2, 4,
       4, 4, 3, 2, 4, 2, 3, 4, 2, 0, 0, 1, 4, 2, 3, 3, 1, 1, 1, 4, 4, 2,
       3, 4, 3, 1, 2, 2, 0, 3, 0, 0, 0, 2, 4, 3, 3, 4, 2, 2, 3, 0, 2, 0,
       1, 0, 3, 3, 4, 1, 2, 3, 0, 2, 1, 2, 4, 0, 1, 0, 4, 0, 2, 1, 0, 4,
       3, 0])

In [39]:
kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(x_random)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



KMeans(n_clusters=5)

In [40]:
rotulos = kmeans_blobs.predict(x_random)
rotulos

array([1, 1, 4, 4, 1, 1, 2, 0, 2, 4, 4, 3, 1, 3, 2, 4, 1, 2, 3, 1, 0, 0,
       2, 2, 3, 4, 1, 3, 4, 4, 4, 4, 4, 0, 3, 2, 3, 2, 0, 0, 0, 2, 2, 4,
       3, 1, 2, 4, 1, 1, 3, 1, 1, 3, 2, 4, 2, 1, 0, 1, 2, 0, 4, 4, 2, 3,
       1, 2, 4, 4, 3, 1, 2, 3, 4, 2, 0, 4, 0, 4, 2, 0, 3, 2, 0, 3, 3, 1,
       1, 0, 2, 0, 3, 2, 0, 4, 1, 2, 3, 3, 2, 3, 4, 1, 0, 4, 3, 2, 3, 0,
       1, 0, 0, 0, 3, 0, 4, 1, 1, 1, 4, 4, 1, 0, 3, 1, 3, 0, 1, 4, 0, 3,
       3, 3, 1, 0, 3, 0, 1, 3, 0, 2, 2, 4, 3, 0, 1, 1, 4, 4, 4, 3, 3, 0,
       1, 3, 1, 4, 0, 0, 2, 1, 2, 2, 2, 0, 3, 1, 1, 3, 0, 0, 1, 2, 0, 2,
       4, 2, 1, 1, 3, 4, 0, 1, 2, 0, 4, 0, 3, 2, 4, 2, 3, 2, 0, 4, 2, 3,
       1, 2], dtype=int32)

In [42]:
centroides = kmeans_blobs.cluster_centers_

In [43]:
centroides

array([[ 4.38467877, -5.50709509],
       [-0.26408822,  2.50457413],
       [-9.5264027 , -9.52709529],
       [ 9.197439  , -7.44029516],
       [ 3.25067692,  5.97631147]])

In [44]:
'''grafico1 = px.scatter(x = x_random[:, 0], y = y_random[:, 1], color = rotulos)
grafico2 = px.scatter(x = centroides[:,0], y=centroides[:, 1], size = [5, 5, 5, 5, 5])
grafico3 = go.Figure(data = grafico1.data)
grafico3.show()'''

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

##Base de dados cartão de crédito

In [45]:
import pandas as pd

###Agrupamento hierárquico

In [47]:
base_cartao = pd.read_csv('credit_card_clients.csv', header= 1)
base_cartao

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...          0          0          0         0       689   
1          0  ...       3272       3455       3261         0      1000   
2          0  ...      14331      14948      15549      1518      1500   
3          0  ...      28314      28959      29547      2000      2019   
4          0  ...      20940      19146      19131      2000     36681   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...      88004      31237      15980      8500     20000   
29996     -1  ...       8979       5190          0      1837      3526   
29997     -1  ...      20878      20582      19357         0         0   
29998      0  ...      52774      11855      48944     85900      3409   
29999      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[30000 rows x 25 columns]

In [48]:
base_cartao['BILL_TOTAL'] = base_cartao['BILL_AMT1'] + base_cartao['BILL_AMT2'] + base_cartao['BILL_AMT3'] + base_cartao['BILL_AMT4'] + base_cartao['BILL_AMT5'] + base_cartao['BILL_AMT6']

In [49]:
base_cartao

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0         -1  ...          0          0         0       689         0   
1          0  ...       3455       3261         0      1000      1000   
2          0  ...      14948      15549      1518      1500      1000   
3          0  ...      28959      29547      2000      2019      1200   
4          0  ...      19146      19131      2000     36681     10000   
...      ...  ...        ...        ...       ...       ...       ...   
29995      0  ...      31237      15980      8500     20000      5003   
29996     -1  ...       5190          0      1837      3526      8998   
29997     -1  ...      20582      19357         0         0     22000   
29998      0  ...      11855      48944     85900      3409      1178   
29999      0  ...      32428      15313      2078      1800      1430   

       PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  BILL_TOTAL  
0             0         0         0                           1        7704  
1          1000         0      2000                           1       17077  
2          1000      1000      5000                           0      101653  
3          1100      1069      1000                           0      231334  
4          9000       689       679                           0      109339  
...         ...       ...       ...                         ...         ...  
29995      3047      5000      1000                           0      725349  
29996       129         0         0                           0       21182  
29997      4200      2000      3100                           1       70496  
29998      1926     52964      1804                           1      266611  
29999      1000      1000      1000                           1      230874  

[30000 rows x 26 columns]

In [50]:
x_cartao = base_cartao.iloc[:, [1, 25]].values
x_cartao

array([[ 20000,   7704],
       [120000,  17077],
       [ 90000, 101653],
       ...,
       [ 30000,  70496],
       [ 80000, 266611],
       [ 50000, 230874]])

In [51]:
scaler_cartao = StandardScaler()
x_cartao = scaler_cartao.fit_transform(x_cartao)

In [52]:
x_cartao

array([[-1.13672015, -0.69069198],
       [-0.3659805 , -0.66599747],
       [-0.59720239, -0.44316987],
       ...,
       [-1.05964618, -0.52525745],
       [-0.67427636, -0.00856436],
       [-0.90549825, -0.10271861]])

In [55]:
wcss = []
for i in range(1, 11):
  kmeans_cartao = KMeans(n_clusters=i, random_state=0)
  kmeans_cartao.fit(x_cartao)
  wcss.append(kmeans_cartao.inertia_)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will chang

In [56]:
wcss


[59999.99999999978,
 35196.57080583435,
 20128.132558347686,
 14943.809173865899,
 10707.537016753624,
 8603.395384848965,
 7400.069599689482,
 6353.473303353463,
 5665.823857740179,
 5052.188166408734]

In [57]:
grafico = px.line(x=range(1, 11), y = wcss)
grafico.show()

In [58]:
kmeans_cartao = KMeans(n_clusters=4, random_state=0)
rotulos = kmeans_cartao.fit_predict(x_cartao)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



In [60]:
grafico = px.scatter(x = x_cartao[:,0], y = x_cartao[:,1], color = rotulos)
grafico.show()

In [62]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [     2, 120000,      2, ...,      1,  17077,      0],
       [     3,  90000,      2, ...,      0, 101653,      0],
       ...,
       [ 29998,  30000,      1, ...,      1,  70496,      0],
       [ 29999,  80000,      1, ...,      1, 266611,      0],
       [ 30000,  50000,      1, ...,      1, 230874,      0]])

In [63]:
lista_clientes = lista_clientes[lista_clientes[:,26].argsort()]

In [64]:
lista_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [ 16789,  30000,      1, ...,      1,  14274,      0],
       [ 16788,  30000,      1, ...,      1,  90453,      0],
       ...,
       [ 20882, 110000,      1, ...,      0, 554308,      3],
       [ 20744, 220000,      1, ...,      0, 452961,      3],
       [ 20270, 150000,      2, ...,      0, 546939,      3]])

##Base de dados cartao de credito - mais atributos

In [66]:
base_cartao.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month', 'BILL_TOTAL'],
      dtype='object')

In [65]:
x_cartao_mais = base_cartao.iloc[:, [1, 2 ,3 ,4 ,25]].values
x_cartao_mais

array([[ 20000,      2,      2,      1,   7704],
       [120000,      2,      2,      2,  17077],
       [ 90000,      2,      2,      2, 101653],
       ...,
       [ 30000,      1,      2,      2,  70496],
       [ 80000,      1,      3,      1, 266611],
       [ 50000,      1,      2,      1, 230874]])

In [68]:
scaler_cartao_mais = StandardScaler()

In [69]:
x_cartao_mais = scaler_cartao_mais.fit_transform(x_cartao_mais)

In [70]:
x_cartao_mais

array([[-1.13672015,  0.81016074,  0.18582826, -1.05729503, -0.69069198],
       [-0.3659805 ,  0.81016074,  0.18582826,  0.85855728, -0.66599747],
       [-0.59720239,  0.81016074,  0.18582826,  0.85855728, -0.44316987],
       ...,
       [-1.05964618, -1.23432296,  0.18582826,  0.85855728, -0.52525745],
       [-0.67427636, -1.23432296,  1.45111372, -1.05729503, -0.00856436],
       [-0.90549825, -1.23432296,  0.18582826, -1.05729503, -0.10271861]])

In [71]:
wcss = []
for i in range(1, 11):
  kmeans_cartao_mais = KMeans(n_clusters=i, random_state=0)
  kmeans_cartao_mais.fit(x_cartao_mais)
  wcss.append(kmeans_cartao_mais.inertia_)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will chang

In [72]:
grafico = px.line(x=range(1, 11), y = wcss)
grafico.show()

In [81]:
kmeans_cartao_mais = KMeans(n_clusters=2, random_state=0)
rotulos = kmeans_cartao_mais.fit_predict(x_cartao_mais)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



In [74]:
rotulos

array([3, 0, 0, ..., 1, 1, 1], dtype=int32)

In [75]:
from sklearn.decomposition import PCA

In [82]:
pca = PCA(n_components=2)
x_cartao_mais_pca = pca.fit_transform(x_cartao_mais)

In [77]:
x_cartao_mais_pca

array([[-1.17389005,  0.81537099],
       [-0.80603045, -0.51172471],
       [-0.84266416, -0.4748328 ],
       ...,
       [-1.22635609, -0.88340566],
       [-0.91767345,  1.42456543],
       [-0.67057781,  0.58582794]])

In [78]:
x_cartao_mais_pca.shape

(30000, 2)

In [83]:
grafico = px.scatter(x = x_cartao_mais_pca[:,0], y = x_cartao_mais_pca[:, 1], color=rotulos)
grafico.show()

In [84]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes = lista_clientes[lista_clientes[:,26].argsort()]
lista_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [ 23817,  50000,      2, ...,      0, 215464,      0],
       [ 14582, 130000,      2, ...,      1, 126994,      0],
       ...,
       [ 13719, 140000,      1, ...,      0,      0,      1],
       [ 13690, 110000,      1, ...,      1, 539465,      1],
       [ 30000,  50000,      1, ...,      1, 230874,      1]])